---
- name: this playbook install packages
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == 'RedHat'
    notify: start apache
 
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"     
    notify: start apache2

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  - name: Ensure the default Apache port is 8082
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen 8082
    when: ansible_os_family == 'RedHat'
    notify: restart apache

  - name: Ensure the default Apache port is 8082
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '^# /etc/apache2/sites-enabled/000-default.conf'
      line: Listen 8082
    when: ansible_os_family == 'Debian'
    notify: restart apache2


  handlers:
  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
  
  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: restart apache
    service:
      name: httpd
      state: restarted

  - name: restart apache2
    service:
      name: apache2
      state: restarted
