---
- name: this playbook uninstall packages
  hosts: all
  become: true
  tasks:
  - name: stop services
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: uninstall httpd service
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

  - name: stop services
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache service
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
