---
- name: install apache2 on ubuntu server
  hosts: dbservers
  become: true
  tasks:
  - name: stop apache2
    service:
      name: apache2
      state: stopped

  - name: uninstall apache2
    apt:
      name: apache2
      state: absent
